import type { Bundler } from '@composable-vite-pwa/unplugin-pwa/node/context-types'
import type { VitePWAStrategy } from '@composable-vite-pwa/unplugin-pwa/node/types'
import type { SWType } from '@composable-vite-pwa/workbox-build/types'
import type { Nuxt } from '@nuxt/schema'
import type { NuxtPWAContext } from '../internal-types'
import type { DtsInfo } from './pwa-icons-helper'
import { normalizePath } from '@composable-vite-pwa/workbox-build/utils/resolve-sw-names'
import { addComponent, addTemplate } from '@nuxt/kit'
import { generatePwaImageType, pwaIcons } from './pwa-icons-helper'

export async function preparePWAIcons<
  B extends Bundler,
  UserStrategy extends VitePWAStrategy,
  T extends SWType,
  NPWAC extends NuxtPWAContext<B, UserStrategy, T>,
>(
  nuxt: Nuxt,
  ctx: NPWAC,
): Promise<DtsInfo | undefined> {
  const pwaAssetsContext = await ctx.pwaAssetsGenerator
  if (!pwaAssetsContext) {
    return undefined
  }
  const assetsInstructions = pwaAssetsContext.instructions()
  const transparentNames = Object.values(assetsInstructions.transparent).map(({ name }) => name)
  const maskableNames = Object.values(assetsInstructions.maskable).map(({ name }) => name)
  const faviconNames = Object.values(assetsInstructions.favicon).map(({ name }) => name)
  const appleNames = Object.values(assetsInstructions.apple).map(({ name }) => name)
  const appleSplashScreenNames = Object.values(assetsInstructions.appleSplashScreen).map(({ name }) => name)
  const dts = {
    dts: pwaIcons({
      transparent: transparentNames,
      maskable: maskableNames,
      favicon: faviconNames,
      apple: appleNames,
      appleSplashScreen: appleSplashScreenNames,
    }),
    transparent: generatePwaImageType('PwaTransparentImageProps', transparentNames),
    maskable: generatePwaImageType('PwaMaskableImageProps', maskableNames),
    favicon: generatePwaImageType('PwaFaviconImageProps', faviconNames),
    apple: generatePwaImageType('PwaAppleImageProps', appleNames),
    appleSplashScreen: generatePwaImageType('PwaAppleSplashScreenImageProps', appleSplashScreenNames),
  } satisfies DtsInfo

  const components: string[] = []
  const names: string[] = []

  const mapTypes = {
    apple: {
      union: appleNames.length > 0
        ? appleNames.map(name => `'${name}'`).join(' | ')
        : 'string',
      validator: appleNames.length > 0
        ? `(value) => [${appleNames.map(name => `'${name}'`).join(', ')}].includes(value)`
        : '(value) => true',
    },
    appleSplashScreen: {
      union: appleSplashScreenNames.length > 0
        ? appleSplashScreenNames.map(name => `'${name}'`).join(' | ')
        : 'string',
      validator: appleSplashScreenNames.length > 0
        ? `(value) => [${appleSplashScreenNames.map(name => `'${name}'`).join(', ')}].includes(value)`
        : '(value) => true',
    },
    favicon: {
      union: faviconNames.length > 0
        ? faviconNames.map(name => `'${name}'`).join(' | ')
        : 'string',
      validator: faviconNames.length > 0
        ? `(value) => [${faviconNames.map(name => `'${name}'`).join(', ')}].includes(value)`
        : '(value) => true',
    },
    maskable: {
      union: maskableNames.length > 0
        ? maskableNames.map(name => `'${name}'`).join(' | ')
        : 'string',
      validator: maskableNames.length > 0
        ? `(value) => [${maskableNames.map(name => `'${name}'`).join(', ')}].includes(value)`
        : '(value) => true',
    },
    transparent: {
      union: transparentNames.length > 0
        ? transparentNames.map(name => `'${name}'`).join(' | ')
        : 'string',
      validator: transparentNames.length > 0
        ? `(value) => [${transparentNames.map(name => `'${name}'`).join(', ')}].includes(value)`
        : '(value) => true',
    },
  } as const

  for (
    const [name, composable, map] of [
      ['PwaAppleImage', 'useApplePwaIcon', 'apple'],
      ['PwaAppleSplashScreenImage', 'useAppleSplashScreenPwaIcon', 'appleSplashScreen'],
      ['PwaFaviconImage', 'useFaviconPwaIcon', 'favicon'],
      ['PwaMaskableImage', 'useMaskablePwaIcon', 'maskable'],
      ['PwaTransparentImage', 'useTransparentPwaIcon', 'transparent'],
    ] as const
  ) {
    names.push(name)
    components.push(addTemplate({
      write: true,
      filename: `pwa-icons/${name}.js`,
      getContents: () => `// Generated by @vite-pwa/nuxt
import { defineComponent, h } from 'vue'
import { ${composable} } from '#pwa'

const ${name} = /* #__PURE__ */ defineComponent({
  name: '${name}',
  inheritAttrs: false,
  props: {
    image: {
      required: true,
      type: String,
      validator: ${mapTypes[map].validator}
    }, 
    width: {
      type: [Number, String],
      required: false
    },
    height: {
      type: [Number, String],
      required: false
    }
  },
  setup(props, { attrs = {} }) {
    const { icon } = ${composable}(props)
    return () => {
      const data = icon.value
      if (!data) {
        return
      }  

      return h('img', Object.assign({}, attrs, data))
    }
  }
})

export default ${name}
`,
    }).filename)
    components.push(addTemplate({
      write: true,
      filename: `pwa-icons/${name}.d.ts`,
      getContents: () => `// Generated by @vite-pwa/nuxt
import type { AllowedComponentProps, ComponentCustomProps, ImgHTMLAttributes, VNodeProps } from 'vue'

export interface ${name}Props extends Omit<ImgHTMLAttributes, 'src'> {
  /**
   * Name of the PWA icon to render.
   * @type {${mapTypes[map].union}}
   */
  image: ${mapTypes[map].union}
}

declare const _default: {
  new (): {
    $props: AllowedComponentProps & ComponentCustomProps & VNodeProps & ${name}Props;
  };
};

export default _default
`,
    }).filename)
  }

  nuxt.options.alias['#pwa-components'] = addTemplate({
    write: true,
    filename: 'pwa-icons/components.ts',
    getContents: () => names.map(name => `export { default as ${name} } from './${name}.js'`).join('\n'),
  }).dst
  nuxt.options.build.transpile.push('#pwa-components')

  for (const name of names) {
    addComponent({
      name,
      filePath: `#build/pwa-icons/${name}`,
    })
  }

  if (nuxt.options.dev/* && nuxt.options.ssr */) {
    // restart nuxt dev server when the configuration files change
    for (const source of pwaAssetsContext.sources()) {
      nuxt.options.watch.push(normalizePath(source))
    }
  }

  return dts
}
