import type { Bundler } from '@composable-vite-pwa/unplugin-pwa/node/context-types'
import type { VitePWAStrategy } from '@composable-vite-pwa/unplugin-pwa/node/types'
import type { SWType } from '@composable-vite-pwa/workbox-build/types'
import type { Nuxt } from '@nuxt/schema'
import type { NuxtPWAContext } from '../internal-types'
import { addPluginTemplate, addTemplate } from '@nuxt/kit'

export interface DtsInfo {
  dts?: string
  transparent?: string
  maskable?: string
  favicon?: string
  apple?: string
  appleSplashScreen?: string
}

export interface PwaIconsTypes {
  transparent?: string[]
  maskable?: string[]
  favicon?: string[]
  apple?: string[]
  appleSplashScreen?: string[]
}

export function addPwaTemplate(
  filename: string,
  content?: string,
): string {
  if (content?.length) {
    return addTemplate({
      write: true,
      filename: `pwa-icons/${filename}.d.ts`,
      getContents: () => content,
    }).filename
  }
  else {
    return addTemplate({
      write: true,
      filename: `pwa-icons/${filename}.d.ts`,
      getContents: () => generatePwaImageType(filename),
    }).filename
  }
}

export function pwaIcons(types?: PwaIconsTypes) {
  return `// Generated by @vite-pwa/nuxt
import type { AppleSplashScreenLink, FaviconLink, HtmlLink, IconAsset } from '@vite-pwa/assets-generator/api'

export interface PWAAssetIconImage {
  width?: number | string
  height?: number | string
  key: string
  src: string
}
export type PWAAssetIcon<T extends HtmlLink> = Omit<IconAsset<T>, 'buffer'> & {
  asImage: PWAAssetIconImage
}
export interface PWAIcons {
  transparent: Record<${generateTypes(types?.transparent)}, PWAAssetIcon<HtmlLink>>
  maskable: Record<${generateTypes(types?.maskable)}, PWAAssetIcon<HtmlLink>>
  favicon: Record<${generateTypes(types?.favicon)}, PWAAssetIcon<FaviconLink>>
  apple: Record<${generateTypes(types?.apple)}, PWAAssetIcon<HtmlLink>>
  appleSplashScreen: Record<${generateTypes(types?.appleSplashScreen)}, PWAAssetIcon<AppleSplashScreenLink>>
}
`
}

export function generatePwaImageType(propsName: string, names?: string[]) {
  return `// Generated by @vite-pwa/nuxt
import type { ImgHTMLAttributes } from 'vue'

export type PWAVueImageType = Omit<ImgHTMLAttributes, 'src'>
  
export type ${propsName} = PWAVueImageType & {
  /**
   * Name of the PWA icon to render.
   * @type {${generateTypes(names)}}
   */
  image: ${generateTypes(names)}
}
`
}

function generateTypes(types?: string[]) {
  return types?.length ? types.map(name => `'${name}'`).join(' | ') : 'string'
}

export function addPWAIconsPluginTemplate<
  B extends Bundler,
  UserStrategy extends VitePWAStrategy,
  T extends SWType,
  NPWAC extends NuxtPWAContext<B, UserStrategy, T>,
>(
  ctx: NPWAC,
  nuxt: Nuxt,
  nuxt4: boolean,
  pwaAssetsEnabled: boolean,
) {
  const buildDir = ctx.nuxt.moduleResolver.resolve(nuxt.options.buildDir, 'pwa-icons')
  const resolvePluginJsPath: (name: string) => string = name => ctx.nuxt.moduleResolver.resolve(
    buildDir,
    name,
  )
  if (nuxt4) {
    addTemplate({
      filename: resolvePluginJsPath('plugin.d.ts'),
      write: true,
      getContents: () => `// Generated by @vite-pwa/nuxt
import type { Plugin } from '#app';
import type { PWAIcons } from '#build/pwa-icons';
declare const plugin: Plugin<{
    pwaIcons?: PWAIcons;
}>;
export default plugin;    
`,
    })

    addPWAIconPluginTemplate(
      resolvePluginJsPath,
      pwaAssetsEnabled,
      'all',
    )
  }
  else {
    addPWAIconPluginTemplate(
      resolvePluginJsPath,
      pwaAssetsEnabled,
      'client',
    )
    addPWAIconPluginTemplate(
      resolvePluginJsPath,
      pwaAssetsEnabled,
      'server',
    )
  }
}

function addPWAIconPluginTemplate(
  resolvePluginJsPath: (name: string) => string,
  pwaAssetsEnabled: boolean,
  mode: 'client' | 'server' | 'all',
) {
  const suffix = mode === 'all' ? '' : `:${mode}`
  const filename = mode === 'all' ? 'plugin' : `plugin.${mode}`
  if (mode !== 'all') {
    addTemplate({
      filename: resolvePluginJsPath(`plugin.${mode}.d.ts`),
      write: true,
      getContents: () => `// Generated by @vite-pwa/nuxt
import type { Plugin } from '#app';
import type { PWAIcons } from '#build/pwa-icons';

declare const plugin: Plugin<{
    pwaIcons?: PWAIcons;
}>;
export default plugin;    
`,
    })
  }
  if (pwaAssetsEnabled) {
    addPluginTemplate({
      filename: resolvePluginJsPath(`${filename}.js`),
      name: `vite-pwa:nuxt:pwa-icons${suffix}:plugin`,
      write: true,
      mode,
      getContents: () => `// Generated by @vite-pwa/nuxt
import { pwaAssetsIcons } from 'virtual:pwa-assets/icons';
import { defineNuxtPlugin } from '#imports';

export default defineNuxtPlugin(() => ({
  provide: {
    pwaIcons: {
      transparent: configureEntry("transparent"),
      maskable: configureEntry("maskable"),
      favicon: configureEntry("favicon"),
      apple: configureEntry("apple"),
      appleSplashScreen: configureEntry("appleSplashScreen")
    }
  }
}))

function configureEntry(key) {
  return Object.values(pwaAssetsIcons[key] ?? {}).reduce((acc, icon) => {
    const entry = Object.assign({}, icon, {
      asImage: {
        src: icon.url,
        key: \`\${key}-\${icon.name}\`
      }
    });
    if (icon.width && icon.height) {
      entry.asImage.width = icon.width;
      entry.asImage.height = icon.height;
    }
    acc[icon.name] = entry;
    return acc;
  }, {});
}
`,
    })
  }
  else {
    addPluginTemplate({
      filename: resolvePluginJsPath(`${filename}.js`),
      name: `vite-pwa:nuxt:pwa-icons${suffix}:plugin`,
      write: true,
      mode,
      getContents: () => `// Generated by @vite-pwa/nuxt
import { defineNuxtPlugin } from '#imports'

export default defineNuxtPlugin(() => ({
  provide: {
    pwaIcons: {
      transparent: {},
      maskable: {},
      favicon: {},
      apple: {},
      appleSplashScreen: {}
    }
  }
}))
`,
    })
  }
}
