import type { Bundler } from '@composable-vite-pwa/unplugin-pwa/node/context-types'
import type { VitePWAStrategy } from '@composable-vite-pwa/unplugin-pwa/node/types'
import type { SWType } from '@composable-vite-pwa/workbox-build/types'
import type { Nuxt } from '@nuxt/schema'
import type { NuxtPWAContext } from '../internal-types'
import type { DtsInfo } from './pwa-icons-helper'
import path from 'node:path'
import { normalizePath } from '@composable-vite-pwa/unplugin-pwa/node/helpers'
import { addTemplate } from '@nuxt/kit'
import { getMajor } from 'verkit'
import { addPWAIconsPluginTemplate, addPwaTemplate, pwaIcons } from './pwa-icons-helper'

export async function registerPwaIconsTypes<
  B extends Bundler,
  UserStrategy extends VitePWAStrategy,
  T extends SWType,
  NPWAC extends NuxtPWAContext<B, UserStrategy, T>,
>(
  ctx: NPWAC,
  nuxt: Nuxt,
) {
  const options = ctx.resolvedOptions
  // we need to resolve first the PWA assets options: the resolved options set at pwa-icons::resolvePWAAssetsOptions
  const pwaAssets = options.pwaAssets && !options.pwaAssets.disabled
  let dts: DtsInfo | undefined
  if (pwaAssets) {
    try {
      const { preparePWAIcons } = await import('./prepare-pwa-icons')
      dts = await preparePWAIcons<B, UserStrategy, T, NPWAC>(nuxt, ctx)
    }
    catch {
      dts = undefined
    }
  }

  const templates: string[] = []

  const dtsContent = dts?.dts
  if (dtsContent) {
    templates.push(addTemplate({
      write: true,
      filename: 'pwa-icons/index.d.ts',
      getContents: () => dtsContent,
    }).filename)
  }
  else {
    templates.push(addTemplate({
      write: true,
      filename: 'pwa-icons/index.d.ts',
      getContents: () => pwaIcons(),
    }).filename)
  }

  templates.push(addPwaTemplate('PwaTransparentImageProps', dts?.transparent))
  templates.push(addPwaTemplate('PwaMaskableImageProps', dts?.maskable))
  templates.push(addPwaTemplate('PwaFaviconImageProps', dts?.favicon))
  templates.push(addPwaTemplate('PwaAppleImageProps', dts?.apple))
  templates.push(addPwaTemplate('PwaAppleSplashScreenImageProps', dts?.appleSplashScreen))

  // register pwa icons plugin
  addPWAIconsPluginTemplate<B, UserStrategy, T, NPWAC>(
    ctx,
    nuxt,
    getMajor(ctx.nuxt.nuxtVersion) >= 4,
    pwaAssets === true,
  )

  const pwaInjectionPath = normalizePath(path.relative(
    ctx.nuxt.moduleResolver.resolve(nuxt.options.buildDir, 'types'),
    ctx.nuxt.moduleResolver.resolve('runtime/plugins/types'),
  ))

  const nuxt5 = getMajor(ctx.nuxt.nuxtVersion) > 4

  // check prepare:types at prepareTypesHook
  addTemplate({
    write: true,
    filename: 'types/pwa-augments.d.ts',
    getContents: () => prepareVueModuleAugmentation(
      pwaInjectionPath,
      nuxt5,
    ),
  })

  const pwaPath = addTemplate({
    filename: 'types/pwa.d.ts',
    write: true,
    getContents: () => templates.map(
      t => `/// <reference path="../${t}" />`,
    ).join('\n'),
  }).dst

  // register types templates
  nuxt.hook('prepare:types', (context) => {
    context.references.push({ path: pwaPath })
    if (getMajor(ctx.nuxt.nuxtVersion) >= 4) {
      context.nodeReferences.push({ path: pwaPath })
    }
  })
}

function prepareVueModuleAugmentation(pwaInjectionPath: string, nuxt5: boolean): string {
  // **DON'T** add export {} with nuxt 5, JetBrains will stop working
  const footer = nuxt5
    ? ''
    : `
export {}
`
  // **DON'T** use here an interface, ctrl + click on vue template won't work with JetBrains/VSCode IDEs
  return `// Generated by @vite-pwa/nuxt
import { UnwrapNestedRefs } from 'vue'
import { PWAIcons } from '#build/pwa-icons'
import { PwaInjection } from '${pwaInjectionPath}'

declare module '#app' {
  interface NuxtApp {
    /**
     * Reactive PWA state and controls provided by \`@vite-pwa/nuxt\`.
     *
     * @example
     * \`\`\`ts
     * const { $pwa } = useNuxtApp()
     * if ($pwa?.needRefresh) await $pwa.updateServiceWorker()
     * \`\`\`
     */
    $pwa?: UnwrapNestedRefs<PwaInjection>
    /**
     * Available PWA icons.
     */
    $pwaIcons?: PWAIcons
  }
}

declare module 'vue' {
  interface ComponentCustomProperties {
    /**
     * Reactive PWA state and controls provided by \`@vite-pwa/nuxt\`.
     *
     * @example
     * \`\`\`ts
     * const { $pwa } = useNuxtApp()
     * if ($pwa?.needRefresh) await $pwa.updateServiceWorker()
     * \`\`\`
     */
    $pwa?: UnwrapNestedRefs<PwaInjection>
    /**
     * Available PWA icons.
     */
    $pwaIcons?: PWAIcons
  }
}
${footer}
`
}
